services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_sherpaticket
    hostname: rabbitmq-sherpaticket
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-/}
    ports:
      - "5672:5672"     # AMQP protocol port
      - "15672:15672"   # Management UI port
    volumes:
      - ./rabbitmq_sherpaticket:/var/lib/rabbitmq
    networks:
      - sherpaticket_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  sherpaticket_net:
    name: sherpaticket_net
    driver: bridge
